// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ9ocqRcuZqXwQSqgwvb7A9MG-UdHEIQ0',
    appId: '1:621412712634:web:dd81ce4767abf8bdb94283',
    messagingSenderId: '621412712634',
    projectId: 'social-media-final-last',
    authDomain: 'social-media-final-last.firebaseapp.com',
    storageBucket: 'social-media-final-last.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpQBCE4VqMcsRoWCG-pGvIONKAVbHm4CU',
    appId: '1:621412712634:android:76656c414e645e65b94283',
    messagingSenderId: '621412712634',
    projectId: 'social-media-final-last',
    storageBucket: 'social-media-final-last.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwypxMhwQfGBZ8geBrzd9TLSL9KxnQgeQ',
    appId: '1:621412712634:ios:c80d066755b14a2cb94283',
    messagingSenderId: '621412712634',
    projectId: 'social-media-final-last',
    storageBucket: 'social-media-final-last.appspot.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwypxMhwQfGBZ8geBrzd9TLSL9KxnQgeQ',
    appId: '1:621412712634:ios:c80d066755b14a2cb94283',
    messagingSenderId: '621412712634',
    projectId: 'social-media-final-last',
    storageBucket: 'social-media-final-last.appspot.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ9ocqRcuZqXwQSqgwvb7A9MG-UdHEIQ0',
    appId: '1:621412712634:web:03a790d51b01154fb94283',
    messagingSenderId: '621412712634',
    projectId: 'social-media-final-last',
    authDomain: 'social-media-final-last.firebaseapp.com',
    storageBucket: 'social-media-final-last.appspot.com',
  );
}
